# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# command section
commands:

# Use a package of configuration called an orb.
orbs:


# Orchestrate or schedule a set of jobs
jobs:

  create_infrastructure:
    docker :
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            aws cloudformation create-stack \
            --stack-name cicd-lessons \
            --region us-east-1 \
            --template-body file://template.yml

  execute_playbook:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["f4:e4:5b:28:26:fd:01:9c:29:bd:48:d1:32:20:19:31"]
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: Configure server
          command: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook -i inventory.txt playbook.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run: apk add --update curl
      - run:
          name: smoke test!
          command: |
            if curl -s --head "ec2-54-159-26-135.compute-1.amazonaws.com:3000"
            then
              echo "reached page!"
              return 0
            else
              echo "failed!"
              return 1
            fi

workflows:
  # Name the workflow "welcome"
  infrastructure:
    # Run the welcome/run job in its own container
    jobs:
      #- create_infrastructure
      - execute_playbook
      - smoke_test:
          requires:
            - execute_playbook
